#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Yuku.AmbilWarna.Resource", IsApplication=false)]

namespace Yuku.AmbilWarna
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int supportsAlpha = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public static int ambilwarna_hsvHeight = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int ambilwarna_hsvWidth = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int ambilwarna_hueWidth = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int ambilwarna_spacer = 2130968579;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int ambilwarna_alphacheckered = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int ambilwarna_alphacheckered_tiled = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int ambilwarna_arrow_down = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int ambilwarna_arrow_right = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int ambilwarna_cursor = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int ambilwarna_hue = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int ambilwarna_target = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public static int ambilwarna_alphaCheckered = 2131034116;
			
			// aapt resource value: 0x7f050007
			public static int ambilwarna_alphaCursor = 2131034119;
			
			// aapt resource value: 0x7f050006
			public static int ambilwarna_cursor = 2131034118;
			
			// aapt resource value: 0x7f050000
			public static int ambilwarna_dialogView = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public static int ambilwarna_newColor = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public static int ambilwarna_oldColor = 2131034122;
			
			// aapt resource value: 0x7f050005
			public static int ambilwarna_overlay = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public static int ambilwarna_pref_widget_box = 2131034124;
			
			// aapt resource value: 0x7f050009
			public static int ambilwarna_state = 2131034121;
			
			// aapt resource value: 0x7f050008
			public static int ambilwarna_target = 2131034120;
			
			// aapt resource value: 0x7f050001
			public static int ambilwarna_viewContainer = 2131034113;
			
			// aapt resource value: 0x7f050003
			public static int ambilwarna_viewHue = 2131034115;
			
			// aapt resource value: 0x7f050002
			public static int ambilwarna_viewSatBri = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int ambilwarna_dialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int ambilwarna_pref_widget = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AmbilWarnaPreference = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public static int AmbilWarnaPreference_supportsAlpha = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
